POST http://localhost:8000/products
Content-Type: application/json
{
  "name": "Product 1",
  "price": 100
}
###
GET http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMyNzc5MjcsInN1YiI6ImQ0ZTMwMjk4LWY2NTUtNDk3ZS1hODdlLTE4NzVmNTMwOTljMiJ9.MkhZQp7TluOmJoMpYj7hPFg_fK2heBqyWBOsb-YonoY
###
GET http://localhost:8000/products/1
###
PUT http://localhost:8000/products/1
Content-Type: application/json
{
  "name": "Product Updated",
  "price": 200
}
###
DELETE http://localhost:8000/products/1

