basePath: /
host: localhost:8000
info:
  contact: {}
  description: Product api with auth
  termsOfService: http://swagger.io/terms
  title: go expert api example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
